#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// Include the FFI bindings generated by build.rs
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_llama_backend_init_safety() {
        // Simple test to ensure the linked library is reachable
        // In a real scenario, this initializes the global llama.cpp state
        unsafe {
            llama_backend_init();
            // Freeing the backend is part of the zero-resource-leak principle
            llama_backend_free();
        }
    }
}