#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// Include the FFI bindings generated by build.rs
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_llama_linked() {
        // Simple test to ensure the linked library is reachable and bindings are valid
        unsafe {
            let _params = llama_model_default_params();
        }
    }
}
